# Load a model

Each model has been developed within a class in the folder models. The name of the 
module represent the name of the dataset. The model contains a class for each architecture.
The constructor of the calss build the model, split the dataset and set all the hyperparameters of the networks.
So the reproducibility is achived by only instanziating the model.


First you have to chose a model and a dataset.  

for instacne: GIN on the GRID dataset

In [11]:
MODEL = "GIN"
DATASET = "BA_2grid"

# import the model
from models.models_BA_2grid import GIN_framework as framework
# import the dataset
from Datasets.synthetics import BA_2grid

In [12]:
# inizialize the framework
dataset = BA_2grid()
gnn = framework(dataset,device="cpu")

In [13]:
# the gnn object contains the train test split and the model.

print(gnn.model)
print(gnn.train_idx)
print(gnn.dataset[gnn.train_idx])

Net(
  (mlp1): Linear(in_features=10, out_features=30, bias=True)
  (conv1): GINConv(nn=Linear(in_features=10, out_features=30, bias=True))
  (mlp2): Linear(in_features=30, out_features=30, bias=True)
  (conv2): GINConv(nn=Linear(in_features=30, out_features=30, bias=True))
  (lin1): Linear(in_features=30, out_features=30, bias=True)
  (lin2): Linear(in_features=30, out_features=2, bias=True)
)
tensor([ 701, 1225,   47,  ...,   40,  423,  494])
BA_2grid(1600)


In [18]:
# right now the model has random weights.
print(gnn.model.mlp1.weight[0])

tensor([-0.1976, -0.0510, -0.2706,  0.1709, -0.0690, -0.2968,  0.0893, -0.2939,
        -0.0626, -0.3027], dtype=torch.float64, grad_fn=<SelectBackward0>)


In [19]:
#now that the model is instaziated, we have to load the weights
gnn.load_model("models/"+DATASET+"_"+MODEL)
print("we loaded the weights")
# right now the model has trained weights.
print(gnn.model.mlp1.weight[0])

we loaded the weights
tensor([-0.1223,  0.3137,  0.0286, -0.1346,  0.3280,  0.3423, -0.0706,  0.1529,
         0.1649, -0.0715], dtype=torch.float64, grad_fn=<SelectBackward0>)


In [20]:
# we also have a build in function to evaluate the model

gnn.evaluate()

Test Loss: 0.000, Train Acc: 1.000 Test Acc: 1.000
